import json
import logging
import os
from datetime import datetime
from importlib import resources
from pathlib import Path
from typing import Dict, Optional, Any, List, Set

import pandas as pd
import numpy as np
from scipy import stats
import scipy
from sklearn import *
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from dotenv import load_dotenv
import litellm

from .utils import (
    check_required_env_vars,
    normalize_prompt,
    generate_sql,
    execute_sql_query,
    upload_file_to_s3,
    get_default_table_fqn,
)

logger = logging.getLogger(__name__)
litellm.drop_params = True


# ===== Config =====
TEMPLATE_NAME = "prompt_to_sql_context_template.jinja"
OUTPUT_DIR = Path("output")
RUN_OUTPUT_PREFIX = ""
FAST_LLM_MODEL = os.environ.get("FAST_LLM", os.environ.get("LITELLM_FAST_MODEL", "azure/gpt-4o-mini"))
SMART_LLM_MODEL = os.environ.get("SMART_LLM", "azure/gpt-5")
SMART_LLM_REASONING_EFFORT = os.environ.get("SMART_LLM_REASONING_EFFORT", "medium")

# Ensure matplotlib is non-interactive for headless environments
load_dotenv()
plt.switch_backend("Agg")

# Default result (always returned)
result = {"type": None, "value": None}
_LAST_SQL_QUERY: Optional[str] = None
_RUN_ID: Optional[str] = None
_QUERY_COUNTER: int = 0
_LAST_CODE_TEXT: Optional[str] = None
_NORMALIZED_PROMPT: Optional[str] = None


def _init_run_context() -> None:
    """Prepare per-run bookkeeping.

    Sets a fresh timestamped run id, resets counters, clears cached prompt/code text,
    and ensures the `output/` directory exists so downstream helpers can persist
    artifacts without additional checks. Honors the optional `RUN_OUTPUT_PREFIX`
    (and the implicit `test_` prefix when running under pytest).
    """
    global _RUN_ID, _QUERY_COUNTER, RUN_OUTPUT_PREFIX, _LAST_CODE_TEXT, _NORMALIZED_PROMPT
    _RUN_ID = datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%S")
    _QUERY_COUNTER = 0
    _LAST_CODE_TEXT = None
    _NORMALIZED_PROMPT = None
    OUTPUT_DIR.mkdir(exist_ok=True)
    prefix = os.environ.get("RUN_OUTPUT_PREFIX")
    if prefix is None and os.environ.get("PYTEST_CURRENT_TEST"):
        prefix = "test_"
    RUN_OUTPUT_PREFIX = prefix or ""


def _next_filename(suffix: str) -> Path:
    """Return an unused artifact path for the current run.

    Args:
        suffix: File suffix (including the leading dot, e.g. ".py").

    Returns:
        Path located under `output/` with the run id (and optional prefix) baked in.
    """
    run_id = _RUN_ID or datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%S")
    base = OUTPUT_DIR / f"{RUN_OUTPUT_PREFIX}tmp_{run_id}{suffix}"
    if not base.exists():
        return base
    index = 1
    while True:
        candidate = OUTPUT_DIR / f"{RUN_OUTPUT_PREFIX}tmp_{run_id}_{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1


def _write_code_snapshot(code: str) -> Path:
    """Persist the generated analysis code.

    Args:
        code: Source text returned by the LLM.

    Returns:
        Path to the saved `.py` file (also cached for inclusion in error messages).
    """
    path = _next_filename(".py")
    path.write_text(code, encoding="utf-8")
    logger.info("Saved generated code to %s", path)
    global _LAST_CODE_TEXT
    _LAST_CODE_TEXT = code
    return path


def _write_query_snapshot(df: Any) -> Optional[Path]:
    """Store a BigQuery result frame as CSV when possible.

    Args:
        df: Object returned by `execute_sql_query`. If it exposes `to_csv`, it will be persisted.

    Returns:
        Path to the CSV snapshot or ``None`` when the object cannot be serialized.
    """
    if not hasattr(df, "to_csv"):
        return None
    global _QUERY_COUNTER
    _QUERY_COUNTER += 1
    path = _next_filename(f"_{_QUERY_COUNTER:02d}.csv")
    df.to_csv(path, index=False)
    logger.info("Saved query result to %s", path)
    return path


def allocate_plot_png_path() -> str:
    """Reserve a PNG filename for plots generated by the LLM-authored code."""
    path = Path(_next_filename(".png"))
    logger.info("Allocated plot PNG path %s", path)
    return str(path)


def allocate_plot_svg_path(png_path: Optional[str] = None) -> str:
    """Reserve an SVG filename for plots generated by the LLM-authored code.

    Args:
        png_path: Optional PNG path previously allocated via ``allocate_plot_png_path``.
            When provided, the SVG path reuses the same stem to keep artefact names aligned.

    Returns:
        String path to the SVG artefact.
    """
    if png_path:
        svg = Path(png_path).with_suffix(".svg")
        logger.info("Allocated plot SVG path %s from PNG %s", svg, png_path)
        return str(svg)

    png = Path(_next_filename(".png"))
    svg = png.with_suffix(".svg")
    logger.info("Allocated standalone plot SVG path %s", svg)
    return str(svg)


def _write_text_snapshot(text: str, suffix: str) -> Path:
    """Persist textual artifacts such as normalized prompts.

    Args:
        text: The content to write.
        suffix: File suffix (e.g. ".txt"). When set to ``.txt`` the text is also cached
            as the run's normalized prompt.

    Returns:
        Path to the written file.
    """
    path = _next_filename(suffix)
    path.write_text(text, encoding="utf-8")
    logger.info("Saved text snapshot to %s", path)
    global _NORMALIZED_PROMPT
    if suffix == ".txt":
        _NORMALIZED_PROMPT = text
    return path


def _write_json_snapshot(payload: Dict[str, Any]) -> Path:
    """Persist the final result dictionary as JSON for later inspection.

    Args:
        payload: JSON-serialisable result dictionary.

    Returns:
        Path to the saved `.json` artifact.
    """
    path = _next_filename(".json")
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    logger.info("Saved JSON snapshot to %s", path)
    return path


def _canonicalize_artifact_path(path: Path) -> Optional[Path]:
    """Reduce duplicate suffixes in artifact filenames prior to upload.

    Args:
        path: Original artifact path emitted by the generated code.

    Returns:
        Canonicalised path with at most one suffix (e.g. ``plot.png`` or
        ``plot.svg``). Returns ``None`` when the original path no longer exists.
    """
    if not path.exists():
        return None

    suffixes = path.suffixes
    if len(suffixes) <= 1:
        return path

    base_name = path.name
    for suffix in suffixes:
        base_name = base_name[: -len(suffix)]

    final_suffix = suffixes[-1]
    if not base_name:
        return path

    canonical_name = f"{base_name}{final_suffix}"
    canonical_path = path.with_name(canonical_name)
    if canonical_path == path:
        return path

    if canonical_path.exists():
        return canonical_path

    try:
        path.rename(canonical_path)
    except OSError as exc:
        logger.warning("Could not canonicalize artifact path %s -> %s: %s", path, canonical_path, exc)
        return path

    return canonical_path


def _tracked_execute_sql_query(sql_query: str) -> pd.DataFrame:
    """Execute SQL while recording context and snapshotting the result.

    Args:
        sql_query: The BigQuery SQL string to execute.

    Returns:
        Pandas DataFrame returned by `execute_sql_query`.
    """
    global _LAST_SQL_QUERY
    _LAST_SQL_QUERY = sql_query
    df = execute_sql_query(sql_query)
    _write_query_snapshot(df)
    return df


def _upload_artifacts_to_s3() -> Dict[str, List[str]]:
    """Upload any artefacts produced in the current run to S3.

    Returns:
        Mapping of artefact-kind (code/csv/prompt/plot/json) to a list of HTTPS S3 URLs.
    """
    uploads: Dict[str, List[str]] = {}
    seen: Set[Path] = set()
    if not _RUN_ID:
        return uploads
    prefix = f"{RUN_OUTPUT_PREFIX}tmp_{_RUN_ID}"
    logger.debug("Scanning artifacts with prefix %s", prefix)
    for path in OUTPUT_DIR.glob(f"{prefix}*"):
        if not path.exists():
            continue
        canonical_path = _canonicalize_artifact_path(path)
        if canonical_path is None or not canonical_path.exists():
            continue
        if canonical_path in seen:
            continue
        suffix = canonical_path.suffix.lower()
        content_type = {
            ".py": "text/x-python",
            ".csv": "text/csv",
            ".txt": "text/plain",
            ".json": "application/json",
            ".png": "image/png",
            ".svg": "image/svg+xml",
        }.get(suffix)
        if suffix == ".py":
            kind = "code"
        elif suffix == ".csv":
            kind = "csv"
        elif suffix == ".txt":
            kind = "prompt"
        elif suffix == ".json":
            kind = "json"
        elif suffix == ".png":
            kind = "plot"
        elif suffix == ".svg":
            kind = "svg"
        else:
            continue
        seen.add(canonical_path)
        url = upload_file_to_s3(str(canonical_path), content_type=content_type)
        uploads.setdefault(kind, []).append(url)
    return uploads


def _inject_artifact_links(result: Dict[str, Any]) -> Dict[str, Any]:
    """Augment the result dictionary with S3 links to all captured artifacts.

    Args:
        result: The result dictionary produced by the LLM-generated code.

    Returns:
        Updated result dictionary with artifact URLs and normalized prompt included.
    """
    uploads = _upload_artifacts_to_s3()
    updated = dict(result)
    if _NORMALIZED_PROMPT:
        updated.setdefault("normalized_prompt", _NORMALIZED_PROMPT)
    if not uploads:
        return updated

    for kind, urls in uploads.items():
        if not urls:
            continue
        if kind == "plot":
            updated["type"] = "plot"
            if urls:
                updated["value"] = urls[0]
        elif kind == "svg":
            if urls:
                updated["svg"] = urls[0] if len(urls) == 1 else urls
        else:
            key = {
                "code": "code",
                "csv": "csv",
            }.get(kind)
            if key:
                updated[key] = urls[0] if len(urls) == 1 else urls
    return updated


def _serialize_value(value: Any) -> Any:
    """Convert complex value types into JSON-safe structures.

    Args:
        value: Arbitrary value from the result dictionary.

    Returns:
        JSON-serialisable equivalent (e.g. list/dict/scalar).
    """
    if isinstance(value, pd.DataFrame):
        return value.to_dict(orient="records")
    numpy_ndarray = getattr(np, "ndarray", tuple)
    numpy_generic = getattr(np, "generic", tuple)
    if isinstance(value, (numpy_ndarray, numpy_generic)):
        return value.tolist() if hasattr(value, "tolist") else value.item()
    if isinstance(value, (set, tuple)):
        return list(value)
    return value


def _to_json_safe(result: Dict[str, Any]) -> Dict[str, Any]:
    """Return a copy of the result dict with the 'value' field JSON-serialised.

    Args:
        result: Raw result dictionary from `_run_pipeline`.

    Returns:
        Dictionary safe to dump via `json.dumps`.
    """
    safe = dict(result)
    safe["value"] = _serialize_value(result.get("value"))
    return safe


def _err(step, detail, input_preview=""):
    """Helper for producing consistent error dictionaries and logging failures.

    Args:
        step: Logical step name (used in logs and error value).
        detail: Error description.
        input_preview: Optional snippet of the input causing the failure.

    Returns:
        Error dictionary with `type="error"`.
    """
    preview = f" | input: '{input_preview}'" if input_preview else ""
    logger.error("%s failure: %s%s", step, detail, preview)
    return {"type": "error", "value": f"ERROR at step '{step}': {detail}{preview}"}


def _read_template(resource_name: str) -> str:
    """Read the code-generation template bundled with the package.

    Args:
        resource_name: Template filename located under ``cdbai.data``.

    Returns:
        Template text.
    """
    try:
        logger.info("Reading prompt template %s from package data", resource_name)
        template_resource = resources.files("cdbai.data") / resource_name
        return template_resource.read_text(encoding="utf-8")
    except Exception as e:
        raise RuntimeError(
            f"Could not read template resource '{resource_name}': {e.__class__.__name__}: {e}"
        ) from e


def _render_template(template_text, *, user_prompt: str, normalized_prompt: str, **extra) -> str:
    """Render the code-generation template with prompt context and extra variables.

    Args:
        template_text: Raw template string.
        user_prompt: Original user prompt.
        normalized_prompt: FlashText-normalised prompt.
        **extra: Additional template variables (e.g. default table FQN).

    Returns:
        Rendered template ready to send to the LLM.
    """
    from jinja2 import Template

    logger.info("Rendering template with normalized prompt")
    template = Template(template_text)
    context = dict(extra)
    context.update({"user_prompt": user_prompt, "normalized_prompt": normalized_prompt})
    return template.render(**context)


def _extract_python_code(text):
    """Extract Python code from a markdown-formatted LLM response.

    Args:
        text: Raw LLM response potentially containing fenced code blocks.

    Returns:
        Extracted Python source (fences stripped) or raw text when no fences exist.
    """
    start = text.find("```")
    if start == -1:
        return text.strip()
    lang_end = text.find("\n", start + 3)
    if lang_end == -1:
        return text.strip()
    end = text.find("```", lang_end + 1)
    if end == -1:
        return text.strip()
    return text[lang_end + 1: end].strip()


def _maybe_correct_prompt(prompt: str) -> str:
    """Use the fast LLM to correct obvious entity spelling mistakes before normalisation.

    Args:
        prompt: Original user prompt.

    Returns:
        Either the corrected prompt or the original when no confident correction existed
        or when the fast LLM is not configured.
    """
    if not FAST_LLM_MODEL:
        return prompt
    system_msg = (
        "You are a domain expert who validates biological prompts. "
        "Fix obvious spelling mistakes in gene symbols, drug names, or cell line identifiers only when certain. "
        "Return the corrected prompt. If unsure about any term, return the original prompt unchanged."
    )
    try:
        response = litellm.completion(
            model=FAST_LLM_MODEL,
            #temperature=0.0,
            messages=[
                {"role": "system", "content": system_msg},
                {"role": "user", "content": prompt},
            ],
        )
        corrected = (response.choices[0].message.content or "").strip()
        if corrected and corrected.lower() != prompt.lower():
            logger.info("Prompt after fast LLM check: %s", corrected)
            return corrected
    except Exception as exc:
        logger.warning("Fast LLM prompt correction failed: %s", exc)
    return prompt


def _exec_user_code(code: str, *, extra_globals: Optional[Dict[str, str]] = None):
    """Execute the LLM-generated analysis code in a controlled environment.

    Args:
        code: Python source emitted by the LLM.
        extra_globals: Additional globals (e.g., prompt strings) exposed to the code.

    Returns:
        Result dictionary produced by the executed code, or an error dictionary when
        execution fails or the `result` variable is missing/malformed.
    """
    logger.info("Executing model-generated code (length=%d)", len(code))
    logger.debug("Model-provided code:\n%s", code)
    _write_code_snapshot(code)
    table_fqn = get_default_table_fqn()
    exec_globals = {
        "__builtins__": __builtins__,
        # Allow full access to safe, whitelisted scientific packages
        "pd": pd,
        "pandas": pd,
        "np": np,
        "scipy": scipy,
        "stats": stats,
        "sklearn": __import__("sklearn"),
        "plt": plt,
        "matplotlib": plt,
        "sns": sns,
        "Image": Image,
        "normalize_prompt": normalize_prompt,
        "generate_sql": generate_sql,
        "execute_sql_query": _tracked_execute_sql_query,
        "DEFAULT_TABLE_FQN": table_fqn,
        "TABLE_FQN": table_fqn,
        "table_fqn": table_fqn,
        "get_default_table_fqn": get_default_table_fqn,
        "allocate_plot_png_path": allocate_plot_png_path,
        "allocate_plot_svg_path": allocate_plot_svg_path,
        "upload_file_to_s3": upload_file_to_s3,
    }

    # Merge any user-provided globals
    if extra_globals:
        exec_globals.update(extra_globals)

    # This avoids the scoping issue where list comprehensions can't see names
    # that were assigned at top level when globals != locals.
    ns = dict(exec_globals)

    try:
        exec(code, ns, ns)
    except Exception as e:
        return _err("exec_user_code", f"{e.__class__.__name__}: {e}", input_preview=code)

    # Retrieve the result safely
    res = ns.get("result")

    if res is None:
        return _err("exec_user_code", "Executed code did not define 'result'.", input_preview=code)
    if not isinstance(res, dict) or "type" not in res or "value" not in res:
        return _err("exec_user_code", "Variable 'result' must be a dict with keys {'type','value'}.", input_preview=str(res))
    return res


def _post_process_result(result: Dict, *, image_content_type: str = "image/png") -> Dict:
    """Handle plot uploads, attach SQL/code on errors, and add artifact links.

    Args:
        result: Result dictionary returned by `_exec_user_code`.
        image_content_type: MIME type to use when uploading plot PNGs.

    Returns:
        Augmented result dictionary ready for JSON serialisation.
    """
    if not isinstance(result, dict):
        return {"type": "error", "value": f"ERROR at step 'post_process': result must be dict, got {type(result)}"}

    result_type = result.get("type")
    value = result.get("value")

    if result_type == "plot" and isinstance(value, str):
        # Plot uploads handled when consolidating artifacts; no action needed here
        pass

    if result_type == "error" and isinstance(value, str):
        if _LAST_SQL_QUERY:
            value = f"{value.rstrip()}\nSQL: {_LAST_SQL_QUERY}"
        if _LAST_CODE_TEXT:
            value = f"{value}\nCode:\n{_LAST_CODE_TEXT}"
        result = {"type": "error", "value": value}

    result = _inject_artifact_links(result)

    return result


def extract_response_text(response: str):
    """ Newer SDKs may have this convenience prop:

    Args:
        response: LiteLLM response from the Responses API

    Returns:
        LLM response text
    """
    text = getattr(response, "output_text", None)
    if text is not None:
        return text

    # Fallback: walk the structured output
    parts = []
    for item in getattr(response, "output", []) or []:
        for block in getattr(item, "content", []) or []:
            if getattr(block, "type", None) == "output_text":
                parts.append(block.text)
    return "".join(parts)


def _call_llm(rendered_prompt: str):
    """Call the smart (and optionally fast) LLM to obtain executable Python code.

    Args:
        rendered_prompt: Prompt string combining context and user request.

    Returns:
        Raw assistant message content containing Python code.

    Raises:
        Exception: When both configured models fail to produce a response.
    """
    model_name = SMART_LLM_MODEL
    reasoning_effort = SMART_LLM_REASONING_EFFORT
    last_exc: Optional[Exception] = None

    try:
        logger.info("Calling litellm model %s", model_name)

        # response = litellm.completion(
        #     model=model_name,
        #     temperature=0.0,
        #     messages=[
        #         {
        #             "role": "system",
        #             "content": (
        #                 "You are a coding assistant. Output ONLY Python code that can be executed directly. "
        #                 "Your code must perform the described analysis and assign a variable named 'result' "
        #                 "with schema: {'type': 'string'|'number'|'dataframe'|'plot'|'error', 'value': ...}. "
        #                 "You may use numpy, scipy, pandas, scikit-learn, matplotlib, seaborn, and pillow — "
        #                 "these are already available. Do not import anything else or print explanations."
        #             ),
        #         },
        #         {"role": "user", "content": rendered_prompt},
        #     ],
        # )
        #assistant_text = response.choices[0].message.content or ""

        response = litellm.responses(
            model=model_name,
            #temperature=0.0,
            input=[{'role': 'system', 'content': (
                        "You are a coding assistant. Output ONLY Python code that can be executed directly. "
                        "Your code must perform the described analysis and assign a variable named 'result' "
                        "with schema: {'type': 'string'|'number'|'dataframe'|'plot'|'error', 'value': ...}. "
                        "You may use numpy, scipy, pandas, scikit-learn, matplotlib, seaborn, and pillow — "
                        "these are already available. Do not import anything else or print explanations."
                    )},
                    {'role': 'user', 'content': rendered_prompt}],
            reasoning={
                "effort": reasoning_effort
            }
        )
        assistant_text = extract_response_text(response) or ""

        logger.info("Model response received (%d chars) using %s", len(assistant_text), model_name)

        return assistant_text
    except Exception as exc:
        logger.warning("Model %s failed: %s", model_name, exc)
        last_exc = exc

    if last_exc:
        raise last_exc

    raise RuntimeError("No LLM models configured")


def _run_pipeline(prompt: str):
    """Core pipeline orchestrating normalisation, LLM execution, BigQuery, and artefact capture.

    Args:
        prompt: Original user prompt.

    Returns:
        Result dictionary produced by the LLM-authored code (error dict on failure).
    """
    result = {"type": None, "value": None}

    try:
        logger.info("Starting pipeline for prompt: %s", prompt)
        _init_run_context()
        check_required_env_vars()
        logger.info("Environment variables validated")
        corrected_prompt = _maybe_correct_prompt(prompt)
        logger.info("Corrected prompt: %s", corrected_prompt)
        normalized_prompt = normalize_prompt(corrected_prompt)
        logger.info("Normalized prompt: %s", normalized_prompt)
        _write_text_snapshot(normalized_prompt, ".txt")
        global _LAST_SQL_QUERY
        _LAST_SQL_QUERY = None

        # 1) Read template file
        try:
            template_text = _read_template(TEMPLATE_NAME)
        except Exception as e:
            result = _err("read_template_file", str(e), input_preview=TEMPLATE_NAME)
            return result

        # 2) Render template with the full user prompt
        try:
            rendered_prompt = _render_template(
                template_text,
                user_prompt=prompt,
                normalized_prompt=normalized_prompt,
                default_table_fqn=get_default_table_fqn(),
            )
        except Exception as e:
            result = _err("render_template", f"{e.__class__.__name__}: {e}", input_preview=template_text)
            return result

        # 3) Send rendered prompt to LLM
        try:
            assistant_text = _call_llm(rendered_prompt)
        except Exception as e:
            result = _err("llm_completion", f"{e.__class__.__name__}: {e}", input_preview=rendered_prompt)
            return result

        if not assistant_text.strip():
            result = {"type": "error", "value": "ERROR at step 'llm_completion': Empty response from model."}
            return result

        # 4) Extract Python code and execute
        try:
            user_code = _extract_python_code(assistant_text)
            if not user_code:
                raise ValueError("No executable code found in model response.")
        except Exception as e:
            result = _err("extract_python_code", f"{e.__class__.__name__}: {e}", input_preview=assistant_text)
            return result

        exec_result = _exec_user_code(
            user_code,
            extra_globals={
                "user_prompt": prompt,
                "normalized_prompt": normalized_prompt,
            },
        )
        result = _post_process_result(exec_result)
        result.setdefault("original_prompt", prompt)
        logger.info("Pipeline completed with result type=%s", result.get("type"))
        return result

    except Exception as e:
        result = _err("unexpected", f"{e.__class__.__name__}: {e}")
        return result


def cdbai_chat(prompt: str) -> Dict[str, Any]:
    """Run the agent for a prompt and return the JSON-safe result dictionary.

    Args:
        prompt: Free-form user prompt describing the desired analysis.

    Returns:
        Dictionary with keys such as `type`, `value`, `normalized_prompt`, `code`, `csv`, etc.
    """
    pipeline_result = _run_pipeline(prompt)
    safe_result = _to_json_safe(pipeline_result)
    _write_json_snapshot(safe_result)

    return safe_result
